# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Does magic
#' @param sample sample
#' @param sample_interval sample interval
#' @return the ACT
calc_act_cpp <- function(sample, sample_interval) {
    .Call('_RBeast_calc_act_cpp', PACKAGE = 'RBeast', sample, sample_interval)
}

